/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.views.operador;

import com.mycompany.dao.WSManager;
import com.mycompany.domain.Calle;
import com.mycompany.domain.Colonia;
import com.mycompany.domain.Zona;
import java.util.ArrayList;

import javax.swing.JOptionPane;

/**
 *
 * @author carlo
 */
public class CreateColoniaForm extends javax.swing.JFrame {

    private Zona zona;
    private PanelZona panelZona;
    /**
     * Creates new form CreateColoniaForm
     */
    public CreateColoniaForm() {
        initComponents();
    }
    
    public CreateColoniaForm(Zona zona, PanelZona panelZona) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.zona = zona;
        this.panelZona = panelZona;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fieldNombreColonia = new javax.swing.JTextField();
        btnCreateColonia = new javax.swing.JButton();
        panelHeader2 = new com.mycompany.vistas.RoundedPanel(20);
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        fieldNombreColonia.setBackground(new java.awt.Color(255, 255, 255));
        fieldNombreColonia.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        fieldNombreColonia.setForeground(new java.awt.Color(0, 153, 255));
        fieldNombreColonia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNombreColoniaActionPerformed(evt);
            }
        });

        btnCreateColonia.setBackground(new java.awt.Color(0, 153, 255));
        btnCreateColonia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCreateColonia.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateColonia.setText("Agregar");
        btnCreateColonia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateColoniaActionPerformed(evt);
            }
        });

        panelHeader2.setBackground(new java.awt.Color(0, 153, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Agregar colonia");

        javax.swing.GroupLayout panelHeader2Layout = new javax.swing.GroupLayout(panelHeader2);
        panelHeader2.setLayout(panelHeader2Layout);
        panelHeader2Layout.setHorizontalGroup(
            panelHeader2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelHeader2Layout.setVerticalGroup(
            panelHeader2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeader2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 255));
        jLabel4.setText("Nombre de la colonia");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHeader2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(fieldNombreColonia)
                    .addComponent(btnCreateColonia, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelHeader2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldNombreColonia, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCreateColonia, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNombreColoniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNombreColoniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNombreColoniaActionPerformed

    private void btnCreateColoniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateColoniaActionPerformed
        // TODO add your handling code here:
        // Obtenemos los datos de los inputs
        String nombreColonia = fieldNombreColonia.getText();

        // verificamos que los campos no esten vacios
        if(nombreColonia.isEmpty()){
            System.out.println("Campos vacios");
            return;
        }

        // Creamos la colonia
        Colonia colonia = new Colonia(nombreColonia, new ArrayList<Calle>(), this.zona.getIdZona());

        // Guardamos la colonia
        int idColonia = WSManager.guardarColonia(colonia);

        if (idColonia != -1) {
            JOptionPane.showMessageDialog(null, "Colonia creada correctamente");
            this.panelZona.initColonias();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Error al crear la colonia");
        }
        
        
        
    }//GEN-LAST:event_btnCreateColoniaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateColoniaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateColoniaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateColoniaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateColoniaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateColoniaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateColonia;
    private javax.swing.JTextField fieldNombreColonia;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelHeader2;
    // End of variables declaration//GEN-END:variables
}
