/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.views.operador;

import com.mycompany.domain.Operador;
import com.mycompany.vistas.Login;
import com.mycompany.vistas.PanelImageRedondeado;


public class HomeOperador extends javax.swing.JFrame {

    private Operador operador;

    /**
     * Creates new form HomeOperador
     */
    public HomeOperador() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }
    
    public HomeOperador(Operador operador) {
        initComponents();
        this.operador = operador;
        this.setLocationRelativeTo(null);
        
        initData();
    }
    
    private void initData() {
        this.labelUsername.setText(this.operador.getNombre_completo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containerHome = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnPedidos = new javax.swing.JButton();
        panelImageLogo7 = new PanelImageRedondeado();
        btnZonas = new javax.swing.JButton();
        bntRepartidores = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        labelUsername = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        containerPedidos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        containerZonas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        containerRepartidores = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        containerHome.setBackground(new java.awt.Color(255, 255, 255));
        containerHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        btnPedidos.setBackground(new java.awt.Color(0, 153, 255));
        btnPedidos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPedidos.setForeground(new java.awt.Color(255, 255, 255));
        btnPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-pedidos.png"))); // NOI18N
        btnPedidos.setText("Pedidos");
        btnPedidos.setBorder(null);
        btnPedidos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidosActionPerformed(evt);
            }
        });

        panelImageLogo7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.jpg"))); // NOI18N

        javax.swing.GroupLayout panelImageLogo7Layout = new javax.swing.GroupLayout(panelImageLogo7);
        panelImageLogo7.setLayout(panelImageLogo7Layout);
        panelImageLogo7Layout.setHorizontalGroup(
            panelImageLogo7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );
        panelImageLogo7Layout.setVerticalGroup(
            panelImageLogo7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );

        btnZonas.setBackground(new java.awt.Color(0, 153, 255));
        btnZonas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnZonas.setForeground(new java.awt.Color(255, 255, 255));
        btnZonas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-zonas.png"))); // NOI18N
        btnZonas.setText("Zonas");
        btnZonas.setBorder(null);
        btnZonas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnZonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonasActionPerformed(evt);
            }
        });

        bntRepartidores.setBackground(new java.awt.Color(0, 153, 255));
        bntRepartidores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntRepartidores.setForeground(new java.awt.Color(255, 255, 255));
        bntRepartidores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-repartidores.png"))); // NOI18N
        bntRepartidores.setText("Repartidores");
        bntRepartidores.setBorder(null);
        bntRepartidores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bntRepartidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRepartidoresActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(0, 153, 255));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-cerrar-sesion.png"))); // NOI18N
        btnLogout.setText("Cerrar sesion");
        btnLogout.setBorder(null);
        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        labelUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelUsername.setForeground(new java.awt.Color(255, 255, 255));
        labelUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUsername.setText("NombreUsuario");
        labelUsername.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addComponent(panelImageLogo7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnZonas, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bntRepartidores, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(panelImageLogo7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelUsername)
                .addGap(28, 28, 28)
                .addComponent(btnPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnZonas, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bntRepartidores, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        containerHome.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 552));

        containerPedidos.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("PEDIDOS");

        javax.swing.GroupLayout containerPedidosLayout = new javax.swing.GroupLayout(containerPedidos);
        containerPedidos.setLayout(containerPedidosLayout);
        containerPedidosLayout.setHorizontalGroup(
            containerPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPedidosLayout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(jLabel1)
                .addContainerGap(314, Short.MAX_VALUE))
        );
        containerPedidosLayout.setVerticalGroup(
            containerPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPedidosLayout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jLabel1)
                .addContainerGap(293, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pedidos", containerPedidos);

        containerZonas.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("ZONAS");

        javax.swing.GroupLayout containerZonasLayout = new javax.swing.GroupLayout(containerZonas);
        containerZonas.setLayout(containerZonasLayout);
        containerZonasLayout.setHorizontalGroup(
            containerZonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerZonasLayout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(jLabel2)
                .addContainerGap(329, Short.MAX_VALUE))
        );
        containerZonasLayout.setVerticalGroup(
            containerZonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerZonasLayout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jLabel2)
                .addContainerGap(293, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Zonas", containerZonas);

        containerRepartidores.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("REPARTIDORES");

        javax.swing.GroupLayout containerRepartidoresLayout = new javax.swing.GroupLayout(containerRepartidores);
        containerRepartidores.setLayout(containerRepartidoresLayout);
        containerRepartidoresLayout.setHorizontalGroup(
            containerRepartidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerRepartidoresLayout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(jLabel3)
                .addContainerGap(264, Short.MAX_VALUE))
        );
        containerRepartidoresLayout.setVerticalGroup(
            containerRepartidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerRepartidoresLayout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jLabel3)
                .addContainerGap(293, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Repartidores", containerRepartidores);

        containerHome.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, -38, -1, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosActionPerformed
        // TODO add your handling code here:
        //Cambio a pestana de pedidos
        this.jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btnPedidosActionPerformed

    private void btnZonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonasActionPerformed
        // TODO add your handling code here:
        this.jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btnZonasActionPerformed

    private void bntRepartidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRepartidoresActionPerformed
        // TODO add your handling code here:
        this.jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_bntRepartidoresActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeOperador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeOperador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeOperador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeOperador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeOperador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntRepartidores;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPedidos;
    private javax.swing.JButton btnZonas;
    private javax.swing.JPanel containerHome;
    private javax.swing.JPanel containerPedidos;
    private javax.swing.JPanel containerRepartidores;
    private javax.swing.JPanel containerZonas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelUsername;
    private org.edisoncor.gui.panel.PanelImage panelImageLogo7;
    // End of variables declaration//GEN-END:variables
}
