/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views.operador;

import com.mycompany.dao.WSManager;
import com.mycompany.domain.EstadoPedido;
import com.mycompany.domain.Pedido;
import com.mycompany.vistas.RoundedPanel;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeFormatterBuilder;
import javax.swing.JOptionPane;

/**
 *
 * @author carlo
 */
public class PanelPedido extends RoundedPanel {

    private Pedido pedido;
    private boolean isEditing = false;

    /**
     * Creates new form PanelPedido
     */
    public PanelPedido() {
        super(20);
        initComponents();
    }

    public PanelPedido(Pedido pedido) {
        super(20);
        initComponents();
        this.pedido = pedido;

        initData();
    }

    private void initData() {
        this.labelIdPedido.setText(String.valueOf(this.pedido.getIdPedido()));
        this.fieldCantidadGarr.setText(String.valueOf(this.pedido.getCantidadGarrafones()));

        // Set selects
        this.comboEstadoPedido.setSelectedItem(this.pedido.getEstado().toString());
        this.comboPrioridad.setSelectedItem(this.pedido.isPrioridad() ? "ALTA" : "NORMAL");

        // Desactivamos fields y selects
        this.fieldCantidadGarr.setEnabled(isEditing);
        this.comboEstadoPedido.setEnabled(isEditing);
        this.comboPrioridad.setEnabled(isEditing);

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy MM dd");
        this.labelFecha.setText("FECHA DEL PEDIDO: " + this.pedido.getFecha().toLocalDate().format(formatter));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containerHeader = new com.mycompany.vistas.RoundedPanel(20);
        jLabel1 = new javax.swing.JLabel();
        labelIdPedido = new javax.swing.JLabel();
        labelIdPedido1 = new javax.swing.JLabel();
        labelIdPedido3 = new javax.swing.JLabel();
        fieldCantidadGarr = new javax.swing.JTextField();
        comboEstadoPedido = new javax.swing.JComboBox<>();
        labelIdPedido4 = new javax.swing.JLabel();
        comboPrioridad = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        labelFecha = new javax.swing.JLabel();
        btnEditarPedido = new javax.swing.JButton();

        setBackground(new java.awt.Color(242, 242, 242));
        setMaximumSize(new java.awt.Dimension(32767, 240));
        setName(""); // NOI18N

        containerHeader.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-pedido-big.png"))); // NOI18N
        jLabel1.setText("Pedido No.");

        labelIdPedido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelIdPedido.setForeground(new java.awt.Color(255, 255, 255));
        labelIdPedido.setText("1214");

        javax.swing.GroupLayout containerHeaderLayout = new javax.swing.GroupLayout(containerHeader);
        containerHeader.setLayout(containerHeaderLayout);
        containerHeaderLayout.setHorizontalGroup(
            containerHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerHeaderLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelIdPedido)
                .addContainerGap(189, Short.MAX_VALUE))
        );
        containerHeaderLayout.setVerticalGroup(
            containerHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerHeaderLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(containerHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelIdPedido))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        labelIdPedido1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelIdPedido1.setForeground(new java.awt.Color(0, 153, 255));
        labelIdPedido1.setText("Cantidad de Garrafones: ");

        labelIdPedido3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelIdPedido3.setForeground(new java.awt.Color(0, 153, 255));
        labelIdPedido3.setText("Estado:");

        fieldCantidadGarr.setBackground(new java.awt.Color(242, 242, 242));
        fieldCantidadGarr.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        fieldCantidadGarr.setForeground(new java.awt.Color(0, 153, 255));
        fieldCantidadGarr.setText("22");
        fieldCantidadGarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCantidadGarrActionPerformed(evt);
            }
        });

        comboEstadoPedido.setBackground(new java.awt.Color(242, 242, 242));
        comboEstadoPedido.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        comboEstadoPedido.setForeground(new java.awt.Color(0, 153, 255));
        comboEstadoPedido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PENDIENTE", "ENTREGADO" }));

        labelIdPedido4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelIdPedido4.setForeground(new java.awt.Color(0, 153, 255));
        labelIdPedido4.setText("Prioridad:");

        comboPrioridad.setBackground(new java.awt.Color(242, 242, 242));
        comboPrioridad.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        comboPrioridad.setForeground(new java.awt.Color(0, 153, 255));
        comboPrioridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NORMAL", "ALTA" }));

        labelFecha.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        labelFecha.setForeground(new java.awt.Color(0, 153, 255));
        labelFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFecha.setText("Fecha");

        btnEditarPedido.setBackground(new java.awt.Color(0, 153, 255));
        btnEditarPedido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditarPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarPedido.setText("Editar");
        btnEditarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelIdPedido4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelIdPedido3)
                                .addGap(18, 18, 18)
                                .addComponent(comboEstadoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelIdPedido1)
                                .addGap(18, 18, 18)
                                .addComponent(fieldCantidadGarr, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEditarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1)))
                .addContainerGap())
            .addComponent(labelFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(containerHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdPedido1)
                    .addComponent(fieldCantidadGarr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdPedido3)
                    .addComponent(comboEstadoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdPedido4)
                    .addComponent(comboPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelFecha)
                .addContainerGap(10, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldCantidadGarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCantidadGarrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCantidadGarrActionPerformed

    private void btnEditarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPedidoActionPerformed
        // TODO add your handling code here:
        if (this.btnEditarPedido.getText().equals("Editar")) {
            this.isEditing = true;
            initData();
            this.btnEditarPedido.setText("Guardar");
        } else if (this.btnEditarPedido.getText().equals("Guardar")) {
            this.isEditing = false;
            this.btnEditarPedido.setText("Editar");
            // Obtenemos los valores de los campos
            int cantidadGarrafones = Integer.parseInt(this.fieldCantidadGarr.getText());
            String estadoString = this.comboEstadoPedido.getSelectedItem().toString();
            
            EstadoPedido estado;
            try {
                estado = EstadoPedido.valueOf(estadoString);
            } catch (IllegalArgumentException ex) {
                JOptionPane.showMessageDialog(null, "El estado del pedido no se encuentra dentro de las opciones");
                System.out.println("Error al parsear estado pedido:" + ex.getMessage());
                return;
            }
            
            String selectedPrioridad = this.comboPrioridad.getSelectedItem().toString();
            boolean prioridad = selectedPrioridad.equalsIgnoreCase("ALTA");
            
            Pedido updatedPedido = this.pedido;
            updatedPedido.setCantidadGarrafones(cantidadGarrafones);
            updatedPedido.setEstado(estado);
            updatedPedido.setPrioridad(prioridad);
            // Actualizamos los datos
            int idPedido = WSManager.actualizarPedido(updatedPedido);
            
            // Verificamos si lo actualizo
            if (idPedido == -1) {
                JOptionPane.showMessageDialog(null, "Error al actualizar el pedido");
                return;
            }
            
            this.pedido = updatedPedido;
            JOptionPane.showMessageDialog(null, "Pedido actualizado con exito");
            initData();
        }

    }//GEN-LAST:event_btnEditarPedidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarPedido;
    private javax.swing.JComboBox<String> comboEstadoPedido;
    private javax.swing.JComboBox<String> comboPrioridad;
    private javax.swing.JPanel containerHeader;
    private javax.swing.JTextField fieldCantidadGarr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelIdPedido;
    private javax.swing.JLabel labelIdPedido1;
    private javax.swing.JLabel labelIdPedido3;
    private javax.swing.JLabel labelIdPedido4;
    // End of variables declaration//GEN-END:variables
}
